### ISSUE TITLE
Exception when trying to edit a layer using GSLFE with borken DB connection

### ISSUE THREAD

**Issue by anguss00** [aodn/geoserver-build#136]
Steps to reproduce:
Run up Geoserver in vagrant with borken DB connection (i.e the default one).
Try to edit a layer using Layer Filters Editor.

Observed behaviour:
Stacktrace complaining about wicket hierarchy issues.

Expected behaviour:
Decent error handling.

**Comment by pmbohm** [comment]
I spent some time on this and realised I am trapped by running this with Jetty. Having no server context causes an error in `lookupGeoServerDataDirectory.java`.

It seems we are stuck with stack traces in the filter pages, however the bug is to show readable messages such as `borken DB connections` in the trace.

**Comment by craigj9** [comment]
In this case, Geoserver would have disabled layers which have broken db connections on startup and they would not be able to be accessed elsewhere in Geoserver.   The layer filter extension shouldn't try to display disabled layers!

**Comment by jonescc** [comment]
In this case, Geoserver would have disabled layers which have broken db connections on startup and they would not be able to be accessed elsewhere in Geoserver.   The layer filter extension shouldn't try to display disabled layers!
