### ISSUE TITLE
Download a subset of the Victorian coastline bathymetry

### ISSUE THREAD

**Issue by smancini** [aodn/geoserver-build#256]
**To reproduce**

Select the following dataset collection "2017 Victorian coastal DEM - Continuous seamless 10m DEM" on the RC AODN Portal
Select a bounding box around port Phillip Bay
Download as NetCDF

**What happens**

Get the following error message
Process failed during execution ucar.ma2.InvalidRangeException: first (-23186) must be >= 0 

See JobID: 99b35702-f9da-4419-8519-0500b97fcc8d created on the 14/09/2017.

**What I expect to happen**

Get the data downloaded

**Comment by jonescc** [comment]
The netcdf java library index class I'm using uses an integer 1D backing array counter causing this error.

I've trialled a replacement for this class that uses a long 1D backing array counter that appears to work with this dataset.   Needs more testing and some cleaning up - can probably implement a chunkiterator now instead of just using a replacement ChunkIndex class.  Refer https://github.com/aodn/geoserver-build/compare/issue-256.
