### ISSUE TITLE
Build includes full web.xml file

### ISSUE THREAD

**Issue by danfruehauf** [aodn/geoserver-build#86]
Current build overrides web.xml. That is to allow overriding of the HTTP 500 error codes (needed for proper squid operation and is very important).

The original solution introduced `web.xml` and added `applicationContextOverrides.xml`, which does the overriding of a bean definition. It is generally not recommended to include the whole web.xml file in our repository but just override the required parts. There must be a better solution for that.

It doesn't quite hurt now, but it'll hurt when we do a version upgrade as `web.xml` will have to be re-imported from the newer version and then apply the changes (something like d159736c58f6963fa8696aa5f8a63461193c2e7b)

**Comment by jonescc** [comment]
A couple of options here:

1) include http status fix in geoserver core
1) include 'override' mechanism in core geoserver web.xml (e.g. include applicationContextOverrides.xml as a placeholder for others to override)

**Comment by danfruehauf** [comment]
> include http status fix in geoserver core

Unfortunately we tried this. From memory, it's part of OGC. We need it because we don't want geoserver to return 200 when errors occurs - otherwise squid will cache it. We probably still need squid, we know what happens without it.

> include 'override' mechanism in core geoserver web.xml (e.g. include applicationContextOverrides.xml as a placeholder for others to override)

That's probably the way to go. They should accept something like that.

**Comment by pblain** [comment]
@jonescc - is it still including web.xml?  Can't see it but maybe I'm looking in the wrong place?

**Comment by jonescc** [comment]
Its still there - https://github.com/aodn/geoserver-build/blob/master/src/main/src/main/webapp/WEB-INF/web.xml

We use this copy of web.xml when building the war so if the geoserver developers ever change its contents  - we won't pick up there changes - this occurred when we last upgraded versions and caused us some issues tracking down what the problem was.

**Comment by julian1** [comment]
Is it not a problem that we don't track upstream? For example - if the underlying Java code actually diverges in ways that are incompatible web.xml and applicationContext.xml. I can remember doing the original 500 error override stuff. If the applicationContext diverged with Geoserver version changes then that would be immediately highlighted using git diff.

**Comment by jonescc** [comment]
Yes. If we were using a fork of geoserver this would be easier to manage.

**Comment by julian1** [comment]
I believe you guys already forked https://github.com/aodn/geoserver - otherwise we would have deleted it.  

The reason to avoid a fork is to minimize the divergence of code changes.

The way to minimize the divergence of our code with upstream Geoserver would have been to harmonize with upstream Geoserver, and then push all our modular extensions upstream - as modular extensions.

Following through that process would have allowed us to un-fork.

**Comment by jonescc** [comment]
GeoWebcache may handle this better than squid. I doubt the geoserver developers would ever allow this 'against spec' change to go into core.

**Comment by pblain** [comment]
We will, hopefully, be moving to geowebcache. We will _definitely_ move to core geoserver. So closing
See https://github.com/aodn/backlog/issues/563
